# Generated by Django 4.1.3 on 2022-12-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_alter_itemcategories_father_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='father_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.itemcategories'),
        ),
    ]
