# Generated by Django 4.1.3 on 2022-12-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0005_item_main_picture_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='compound',
            field=models.TextField(verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='father_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.itemcategories', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.TextField(verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Сокрщение для ссылки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.types', verbose_name='Тип'),
        ),
    ]
