# Generated by Django 4.1.3 on 2022-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0006_alter_item_compound_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sort',
            field=models.IntegerField(default=10, verbose_name='Индекс сортировки'),
            preserve_default=False,
        ),
    ]
