# Generated by Django 4.1.3 on 2022-12-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0007_item_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='similar_items',
            field=models.ManyToManyField(to='cosmetics.item'),
        ),
    ]
