# Generated by Django 4.1.3 on 2022-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0008_item_similar_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='similar_items',
            field=models.ManyToManyField(blank=True, null=True, to='cosmetics.item', verbose_name='Похожие товары'),
        ),
    ]
