# Generated by Django 4.1.3 on 2023-01-05 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0011_remove_callbackform_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
