# Generated by Django 4.1.3 on 2023-01-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0013_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.CharField(max_length=60, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=60, verbose_name='Номер дома'),
        ),
    ]
