# Generated by Django 4.1.3 on 2023-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0014_order_payed_alter_order_flat_alter_order_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
